config/routes.rb
Rails.application.routes.draw do

root "pages#index"

resources :pages
resources :faq
resources :registrations
resources :services
resources :users

end

app/models/faq.rb
class Faq < ActiveRecord::Base

end

app/models/page.rb
class Page < ActiveRecord::Base

end

app/models/registration.rb
class Registration < ActiveRecord::Base

end

app/models/service.rb
class Service < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController

  def index
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(
      :first_name, :last_name, :email_address, :password, :password_confirmation
      ))
      @user.save
      session[:user_id] = @user.id
      redirect_to root_path
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
    :first_name,
    :last_name,
    :email_address,
    :password,
    :password_confirmation
    )
  end

  def create
      @user = User.new(user_params)
      @user.save
      redirect_to root_path, notice: 'User was successfully created.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/faq/index.html.erb
This is the FAQ page

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meecro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
   <div class="navbar navbar-inverse navbar-fixed-top" >
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><strong>Meecro</strong></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <%= link_to "Home", pages_path %>
                    <%= link_to "Services", services_path %>
                    <%= link_to "FAQ", faq_index_path %>
                    <%= link_to "Sign Up", new_registration_path %>
                    <%= link_to "Log In" %>
                </ul>
            </div>
        </div>
    </div>
<%= yield %>


<footer class="navbar-fixed-bottom">
      <div class = "container">
        <hr>
      <%= link_to_unless_current "About" %> |
      <%= link_to_unless_current "Terms" %> |
      <%= link_to_unless_current "FAQ" %> |
      <%= link_to_unless_current "Support" %>

        <div class = "icons">
        </div>
      </div>
    </footer>
    <%= javascript_include_tag 'application' %>


</body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron text-center">
  <h3>Welcome to Meecro</h3>
      <p>The premier web app to manage your life</p>

</div>

app/views/services/index.html.erb
Services page!